### ISSUE TITLE
SFTP Error Handling

### ISSUE THREAD

**Issue by Dman247** [halcyon-tech/vscode-ibmi#325]
# One day, seemingly out of the blue, I was not able to use this extension. I was getting an error loading members:
![image](https://user-images.githubusercontent.com/38368303/134549440-78731846-8bcf-4894-8ff3-12600bf2df8e.png)

# I pulled the code and debugged the extension and narrowed it down to this call inside the getTable function:
https://github.com/halcyon-tech/vscode-ibmi/blob/a59efd81fa288b92695e641ccff229c40782308e/src/api/IBMiContent.js#L180

# This ends up throwing an error that gets caught here:
https://github.com/halcyon-tech/vscode-ibmi/blob/a59efd81fa288b92695e641ccff229c40782308e/src/views/memberBrowser.js#L489-L494

# And dumps out this:
```
Error: Unexpected packet before version
    at SFTPStream._transform (c:\Users\dhague\src\repo\vscode-ibmi\node_modules\ssh2-streams\lib\sftp.js:306:1)
    at SFTPStream.<anonymous> (internal/streams/transform.js:205:10)
    at SFTPStream._read (c:\Users\dhague\src\repo\vscode-ibmi\node_modules\ssh2-streams\lib\sftp.js:183:1)
    at SFTPStream._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at SFTPStream.write (internal/streams/writable.js:303:10)
    at Channel.ondata (internal/streams/readable.js:719:22)
    at Channel.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Channel.push (internal/streams/readable.js:223:10)
    at SSH2Stream.<anonymous> (c:\Users\dhague\src\repo\vscode-ibmi\node_modules\ssh2\lib\Channel.js:167:1)
    at SSH2Stream.emit (events.js:315:20)
    at parsePacket (c:\Users\dhague\src\repo\vscode-ibmi\node_modules\ssh2-streams\lib\ssh.js:3191:1)
    at SSH2Stream._transform (c:\Users\dhague\src\repo\vscode-ibmi\node_modules\ssh2-streams\lib\ssh.js:701:1)
    at SSH2Stream.<anonymous> (internal/streams/transform.js:205:10)
    at SSH2Stream._read (c:\Users\dhague\src\repo\vscode-ibmi\node_modules\ssh2-streams\lib\ssh.js:253:1)
    at SSH2Stream._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at SSH2Stream.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:131:14)
```
# The troubleshooting from there after was working with NodeSSH and SFTP. Which I finally find something helpful here:
https://web.archive.org/web/20160114130008/http://www.openssh.com:80/faq.html#2.9
![image](https://user-images.githubusercontent.com/38368303/134561231-aed5f2a0-b0a8-4f08-b208-090179f60fc2.png)

# Aha Moment
This was my 'a-ha' moment as I did recently change my ~/.bahsrc file on the IMBi to pump out some general output. 
And sure enough, when I toggle the ~/.bashrc file between writing to stdout and not writing to stdout, I am seeing the issue appear/disappear (respectively). 

The best solution, for me, is to keep the shell initialization that writes to stdout in my ~/.profile file which will not execute via an SFTP connection. That, however, is outside the scope of this extension.

# Problem
However, without debugging the extension, the user doesn't have good direction to troubleshoot what's going wrong with their SFTP connection.

# Potential Solution
## Better Visibility 
Slight code mod here:
https://github.com/halcyon-tech/vscode-ibmi/blob/a59efd81fa288b92695e641ccff229c40782308e/src/views/memberBrowser.js#L489-L494
For a quick solution, the showErrorMessage will display a useful(googleable) message when passed in `e.message` rather than `e`.

![image](https://user-images.githubusercontent.com/38368303/134624009-96ff6726-167e-42c1-8229-c689af20e52a.png)

**Comment by priceaj** [comment]
If this will give users more visibility of errors, why don't you submit a PR for review with the code change?
