### ISSUE TITLE
Snippets Not Working

### ISSUE THREAD

**Issue by mattlavinder** [halcyon-tech/vscode-ibmi#514]
**Describe the bug**
I have been trying to test out code snippets, and I cannot seem to get them to work.  I type in %scan and I do not see anything like the documentation suggest.

**To Reproduce**

This is tricky, but here is what I can tell you:
- The function I am testing with is `%scan` because it is the one you use in your examples
- I am on a Mac, but I tried this on a Windows VM and had the same issue
- I have the latest version of VS Code and the latest version of the extension
- I disabled ALL my extensions and ONLY enabled the Code for IBM i and I still experienced the issue
- I downloaded an RPGLE file to my local drive and, when I opened it, I experienced the same issue

**Expected behavior**
- Snippets should appear when typing a known built in RPGLE functions

**Screenshots**
I am getting console errors, but I am not entirely sure they are relevant:

```
console.ts:137 [Extension Host] DMIMATT/QRPGSRC/TESTPGM2.RPGLE
console.ts:137 [Extension Host] DMIMATT/QRPGSRC/TESTPGM2.RPGLE
log.ts:313   ERR this._getFsProvider(...).watch is not a function: TypeError: this._getFsProvider(...).watch is not a function
	at l.$watch (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:80601)
	at i._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:13801)
	at i._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:13485)
	at i._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:12147)
	at i._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:10825)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:8934
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
	at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:19002)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:112:34390
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
	at s.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:19002)
	at a._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:23583)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:21117
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
	at _.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:15833)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:14963
	at Socket.A (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:112:13838)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
console.ts:137 [Extension Host] Error: Could NOT open editor for "member:/DMIMATT/QRPGSRC/TESTPGM2.RPGLE".	at D.showTextDocument (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:65822)	at processTicksAndRejections (internal/process/task_queues.js:93:5)	at async /Users/mlavinder/.vscode/extensions/halcyontechltd.code-for-ibmi-0.8.31/dist/extension.js:2:597133	at async u._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:30224)	at async u._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:30224)
```

**Environment (please complete the following information):**
 - Extension version v0.8.31
 - IBM i OS version 7.4
 - VS Code Version  1.64.0
 - Mac Version 12.2
 - Windows 10 (on VM I tested with)

**Additional Information**
Apologies if this doesn't wind up being a bug. I have done a lot a reading up on snippets and have been experimenting because I really did not want to create this issue. I feel like I am probably missing something, but I am not sure what else I could try at this point.

**Comment by worksofliam** [comment]
Do you mean the RPGLE snippets? Because those come from a different extension: RPGLE language tools (vscode-rpgle)
